#Docker Compose

services:
  admin:
    build: ./admin
    container_name: admin_app
    restart: always
    ports:
      - '3001:3000' # ou a porta que seu app usa internamente
    networks:
      - engajame-network

  site-core-pilates:
    build: ./site-core-pilates
    container_name: site_core_pilates
    restart: always
    ports:
      - '3002:3000'
    networks:
      - engajame-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/proxy_params:/etc/nginx/proxy_params
    depends_on:
      - admin
      - site-core-pilates
    networks:
      - engajame-network

networks:
  engajame-network:
    driver: bridge
